package com.ub.dataanalyzer.server.utility;

public enum ParserServiceType {
	GENERAL,CODE_INFO,CO_ORDINATE_INFO,GROUP_INFO,NEIGHBOR_INFO,
	REGION_INFO,FAO_INFO,CAPITAL_INFO,MAP_SHOW,
	GDP,HDI,POPULATION,AREA,LAND_AREA,AGRICULTURAL_AREA
	
}
